name: CI Regression

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test dependencies
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev build-essential
          python -m pip install --upgrade pip
          pip install https://github.com/rasterio/rasterio/archive/master.zip
      - name: Run CI tests
        run: bash test.sh
        shell: bash
